import { useEffect, useState, useRef } from "react";

// AI-generated luxury light-theme imagery (Gemini Nano Banana, golden hour editorial style).
// Generated by /app/backend/gen_hero_images.py — Sotheby's / Aman Residences caliber.
const SLIDES = [
  { src: "/images/luxe/biswa_bangla_gate.jpg", caption: "Biswa Bangla Gate · New Town" },
  { src: "/images/luxe/howrah_bridge.jpg", caption: "Rabindra Setu · Howrah Bridge" },
  { src: "/images/luxe/victoria_memorial.jpg", caption: "Victoria Memorial · Kolkata" },
  { src: "/images/luxe/new_town_skyline.jpg", caption: "New Town Skyline" },
  { src: "/images/luxe/luxury_villa.jpg", caption: "Curated Luxury Residences" },
];

const VISIBLE_MS = 4000;
const FADE_MS = 1000;
const CYCLE_MS = VISIBLE_MS + FADE_MS;

export default function CinematicHero() {
  const [idx, setIdx] = useState(0);
  const preloaded = useRef(new Set());

  // Preload ALL images immediately on mount so transitions never wait on network.
  useEffect(() => {
    SLIDES.forEach((s) => {
      if (preloaded.current.has(s.src)) return;
      const img = new Image();
      img.src = s.src;
      preloaded.current.add(s.src);
    });
  }, []);

  useEffect(() => {
    const t = setInterval(() => setIdx((i) => (i + 1) % SLIDES.length), CYCLE_MS);
    return () => clearInterval(t);
  }, []);

  return (
    <div className="absolute inset-0 overflow-hidden bg-[#050505]">
      {/* All slides rendered simultaneously — only opacity toggles.
          No mount/unmount → no black flash, true cross-fade. */}
      {SLIDES.map((slide, i) => {
        const active = i === idx;
        return (
          <div
            key={slide.src}
            className="absolute inset-0"
            style={{
              opacity: active ? 1 : 0,
              transition: `opacity ${FADE_MS}ms cubic-bezier(0.22, 1, 0.36, 1)`,
              // Ken Burns zoom — runs only while active, resets when slide hides
              transform: active ? "scale(1.10)" : "scale(1.04)",
              transitionProperty: "opacity, transform",
              transitionDuration: `${FADE_MS}ms, ${CYCLE_MS + FADE_MS}ms`,
              transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1), linear",
              willChange: "opacity, transform",
            }}
          >
            <img
              src={slide.src}
              alt={slide.caption}
              loading={i === 0 ? "eager" : "eager"}
              fetchPriority={i === 0 ? "high" : "auto"}
              decoding="async"
              className="w-full h-full object-cover"
              style={{ filter: "saturate(1.08) contrast(1.04) brightness(0.96)" }}
            />
          </div>
        );
      })}

      {/* Bottom fade — blends photograph into the ivory page below.
          This is not a text overlay; it's how the image dissolves into the next section. */}
      <div
        className="absolute inset-x-0 bottom-0 h-[38%] pointer-events-none"
        style={{ background: "linear-gradient(180deg, rgba(250,248,245,0.0) 0%, rgba(250,248,245,0.55) 70%, #FAF8F5 100%)" }}
      />

      {/* Mobile-only readability gradient — at small widths there is less photographic
          real-estate around the text. Desktop has NO overlay; the photograph reads
          naturally as an editorial cover. */}
      <div
        className="absolute inset-0 pointer-events-none md:hidden"
        style={{
          background:
            "linear-gradient(90deg, rgba(26,26,26,0.27) 0%, rgba(26,26,26,0.18) 18%, rgba(26,26,26,0.08) 38%, rgba(26,26,26,0.02) 60%, transparent 80%)",
        }}
      />

      {/* Slide caption + progress dots — bottom right (desktop only) */}
      <div className="absolute bottom-8 right-8 lg:right-16 hidden md:flex flex-col items-end gap-3 pointer-events-none z-10">
        <div
          className="text-[10px] tracking-[0.4em] uppercase text-[#1C1C1C]/70 font-medium"
        >
          {SLIDES[idx].caption}
        </div>
        <div className="flex gap-1.5">
          {SLIDES.map((s, i) => (
            <span
              key={s.src}
              className={`h-px transition-all duration-500 ${
                i === idx ? "w-8 bg-copper" : "w-4 bg-[#1C1C1C]/20"
              }`}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
