import { useEffect, useState, useRef } from "react";

// AI-generated luxury light-theme imagery (Gemini Nano Banana, golden hour editorial style).
// Generated by /app/backend/gen_hero_images.py — Sotheby's / Aman Residences caliber.
//
// `mobilePos` / `desktopPos` control object-position per slide so the architectural
// focal point stays in frame on narrow portrait viewports (where the wide source
// image is otherwise cropped to roughly the centre 35–40%).
const SLIDES = [
  {
    src: "/images/luxe/biswa_bangla_gate.jpg",
    caption: "Biswa Bangla Gate · New Town",
    mobilePos: "50% 40%",   // keep the gate arch + crown visible
    desktopPos: "50% 50%",
  },
  {
    src: "/images/luxe/howrah_bridge.jpg",
    caption: "Rabindra Setu · Howrah Bridge",
    mobilePos: "55% 45%",   // bridge cantilevers sit centre-right
    desktopPos: "50% 50%",
  },
  {
    src: "/images/luxe/victoria_memorial.jpg",
    caption: "Victoria Memorial · Kolkata",
    mobilePos: "50% 38%",   // pull the dome up so it doesn't get clipped
    desktopPos: "50% 45%",
  },
  {
    src: "/images/luxe/new_town_skyline.jpg",
    caption: "New Town Skyline",
    mobilePos: "62% 55%",   // tall towers cluster right of frame
    desktopPos: "50% 50%",
  },
  {
    src: "/images/luxe/luxury_villa.jpg",
    caption: "Curated Luxury Residences",
    mobilePos: "58% 50%",   // villa facade — centre-right
    desktopPos: "50% 50%",
  },
];

const VISIBLE_MS = 4000;
const FADE_MS = 1000;
const CYCLE_MS = VISIBLE_MS + FADE_MS;
// The first transition fires earlier than the regular cadence so the user
// sees the carousel come alive within ~3.2s of landing — no "static hero"
// pause. Subsequent slides revert to the calmer 5s cycle.
const FIRST_TRANSITION_MS = 3200;

// Per-slide object-position rules emitted as a single CSS block so the focal
// point is selected purely by the viewport width — no JS state, no resize
// listener, works under SSR and any screenshot tool.
const RESPONSIVE_POSITION_CSS = `
  ${SLIDES.map((s, i) => `.cinematic-slide-${i} { object-position: ${s.desktopPos}; }`).join("\n  ")}
  @media (max-width: 767px) {
  ${SLIDES.map((s, i) => `  .cinematic-slide-${i} { object-position: ${s.mobilePos}; }`).join("\n  ")}
  }
`;

export default function CinematicHero() {
  const [idx, setIdx] = useState(0);
  // `mounted` flips true one frame after first render — this lets every slide
  // (including slide 0) animate FROM scale(1.04) TO scale(1.10), instead of
  // appearing frozen at the end-state on initial paint.
  const [mounted, setMounted] = useState(false);
  const preloaded = useRef(new Set());
  const intervalRef = useRef(null);

  // Preload ALL images immediately on mount so transitions never wait on network.
  // Slide 0 already gets fetchPriority=high via the rendered <img>; we add a
  // hidden <link rel="preload"> for slide 1 so the first transition has the
  // next image fully decoded before the swap.
  useEffect(() => {
    // Pick the WebP variant that matches the viewport so we don't waste
    // ~150KB on mobile downloading the desktop-sized image.
    const isMobile =
      typeof window !== "undefined" && window.innerWidth <= 768;
    SLIDES.forEach((s, i) => {
      if (preloaded.current.has(s.src)) return;
      const url = s.src.replace(
        /\.(jpe?g|png)$/i,
        isMobile ? "-mobile.webp" : ".webp"
      );
      const img = new Image();
      if (i <= 1 && "fetchPriority" in img) {
        img.fetchPriority = "high";
      }
      img.decoding = "async";
      img.src = url;
      preloaded.current.add(s.src);
    });
  }, []);

  useEffect(() => {
    // Double-rAF: paint once at scale(1.04), then on the next frame flip
    // `mounted` so React updates style to scale(1.10) — the browser now sees
    // a value change and animates the Ken Burns zoom on slide 0 from mount.
    let raf2 = 0;
    const raf1 = requestAnimationFrame(() => {
      raf2 = requestAnimationFrame(() => setMounted(true));
    });
    return () => {
      cancelAnimationFrame(raf1);
      if (raf2) cancelAnimationFrame(raf2);
    };
  }, []);

  useEffect(() => {
    // First transition: fire at ~3.2s so motion starts feeling alive quickly.
    const first = setTimeout(() => {
      setIdx((i) => (i + 1) % SLIDES.length);
      // Then settle into the calm 5s cadence.
      intervalRef.current = setInterval(
        () => setIdx((i) => (i + 1) % SLIDES.length),
        CYCLE_MS
      );
    }, FIRST_TRANSITION_MS);
    return () => {
      clearTimeout(first);
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, []);

  return (
    <div className="absolute inset-0 overflow-hidden bg-[#050505]">
      {/* Per-slide responsive object-position rules — pure CSS, no JS state. */}
      <style>{RESPONSIVE_POSITION_CSS}</style>

      {/* All slides rendered simultaneously — only opacity toggles.
          No mount/unmount → no black flash, true cross-fade. */}
      {SLIDES.map((slide, i) => {
        const active = i === idx;
        return (
          <div
            key={slide.src}
            className="absolute inset-0"
            style={{
              opacity: active ? 1 : 0,
              transition: `opacity ${FADE_MS}ms cubic-bezier(0.22, 1, 0.36, 1)`,
              // Ken Burns zoom — every active slide (including slide 0 on the
              // very first paint) animates from 1.04 → 1.10. `mounted` flips
              // true one frame after first render so React produces a value
              // change the browser can interpolate.
              transform: active && mounted ? "scale(1.10)" : "scale(1.04)",
              transitionProperty: "opacity, transform",
              transitionDuration: `${FADE_MS}ms, ${CYCLE_MS + FADE_MS}ms`,
              transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1), linear",
              willChange: "opacity, transform",
            }}
          >
            <picture>
              <source
                type="image/webp"
                media="(max-width: 768px)"
                srcSet={slide.src.replace(/\.(jpe?g|png)$/i, "-mobile.webp")}
              />
              <source
                type="image/webp"
                srcSet={slide.src.replace(/\.(jpe?g|png)$/i, ".webp")}
              />
              <img
                src={slide.src}
                alt={slide.caption}
                loading="eager"
                fetchPriority={i <= 1 ? "high" : "auto"}
                decoding="async"
                className={`w-full h-full object-cover cinematic-slide-${i}`}
                style={{ filter: "saturate(1.08) contrast(1.04) brightness(0.96)" }}
              />
            </picture>
          </div>
        );
      })}

      {/* Bottom fade — blends photograph into the ivory page below.
          This is not a text overlay; it's how the image dissolves into the next section. */}
      <div
        className="absolute inset-x-0 bottom-0 h-[38%] pointer-events-none"
        style={{ background: "linear-gradient(180deg, rgba(250,248,245,0.0) 0%, rgba(250,248,245,0.55) 70%, #FAF8F5 100%)" }}
      />

      {/* Soft dark gradient on the left edge of every slide — guarantees the
          headline reads cleanly on bright / warm-toned slides (Victoria Memorial,
          Luxury Villa, Howrah Bridge, etc.) without dimming the photograph. */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            "linear-gradient(90deg, rgba(0,0,0,0.45) 0%, rgba(0,0,0,0.20) 40%, rgba(0,0,0,0) 100%)",
        }}
      />

      {/* Slide caption + progress dots — bottom right (desktop only) */}
      <div className="absolute bottom-8 right-8 lg:right-16 hidden md:flex flex-col items-end gap-3 pointer-events-none z-10">
        <div
          className="text-[10px] tracking-[0.4em] uppercase text-[#1C1C1C]/70 font-medium"
        >
          {SLIDES[idx].caption}
        </div>
        <div className="flex gap-1.5">
          {SLIDES.map((s, i) => (
            <span
              key={s.src}
              className={`h-px transition-all duration-500 ${
                i === idx ? "w-8 bg-copper" : "w-4 bg-[#1C1C1C]/20"
              }`}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
